// app/api/llms-txt/route.ts
//
// Builds an llms.txt from what the site actually publishes.
//
// The previous "generator" was string interpolation into a hardcoded template
// that described an enterprise networking vendor, so every domain produced copy
// unrelated to its own business. This fetches the homepage, reads the title,
// description and internal links, and emits a file that reflects the real site.
//
// It is deliberately conservative: it only claims what it can see on one page,
// and it says so in the generated file.
import { NextResponse } from "next/server";
import { fetchText, inspectTarget } from "@/lib/net/fetch-safe";
import { clientKey, takeToken } from "@/lib/net/rate-limit";
import { SITE_URL } from "@/lib/site";

export const runtime = "edge";
export const dynamic = "force-dynamic";

const UA = `Mozilla/5.0 (compatible; LLMentionBot/1.0; +${SITE_URL}/methodology/)`;

const FETCH_TIMEOUT_MS = 9000;
const MAX_LINKS = 12;

/**
 * Boilerplate for the generated file, in the language of the studio the reader
 * is using.
 *
 * The German studio used to hand back an English file: German headings, German
 * buttons, and then "## Key pages" and English notes inside the document a
 * German site owner is meant to publish. The fetched content already follows
 * Accept-Language, so the scaffolding around it has to follow the same signal.
 */
type OutputLabels = {
  intro: (name: string, origin: string) => string;
  keyPages: string;
  homeFallback: (origin: string) => string;
  notes: string;
  generatedBy: (date: string, origin: string) => string;
  review: string;
  convention: string;
};

const OUTPUT_LABELS: Record<string, OutputLabels> = {
  en: {
    intro: (name, origin) =>
      `${name} is published at ${origin}. This file lists the pages an AI system should read first.`,
    keyPages: "## Key pages",
    homeFallback: (origin) => `- [Home](${origin}/): the site homepage.`,
    notes: "## Notes",
    generatedBy: (date, origin) =>
      `- Generated by LLMention on ${date} from the links found on ${origin}/.`,
    review:
      "- Review and edit before publishing: these are only the pages reachable from the homepage, and the descriptions are the link texts as written.",
    convention: "- Convention reference: https://llmstxt.org/",
  },
  de: {
    intro: (name, origin) =>
      `${name} ist unter ${origin} veröffentlicht. Diese Datei nennt die Seiten, die ein KI-System zuerst lesen sollte.`,
    keyPages: "## Wichtige Seiten",
    homeFallback: (origin) => `- [Startseite](${origin}/): die Startseite der Website.`,
    notes: "## Hinweise",
    generatedBy: (date, origin) =>
      `- Erzeugt von LLMention am ${date} aus den Links auf ${origin}/.`,
    review:
      "- Vor der Veröffentlichung prüfen und anpassen: Dies sind nur die von der Startseite erreichbaren Seiten, und die Beschreibungen sind die Linktexte im Originalwortlaut.",
    convention: "- Referenz zur Konvention: https://llmstxt.org/",
  },
};

function cleanDomain(input: string): string {
  return input
    .trim()
    .replace(/^https?:\/\//i, "")
    .replace(/^www\./i, "")
    .split("/")[0]
    .split("?")[0]
    .toLowerCase();
}

function decodeEntities(input: string): string {
  return input
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&apos;/gi, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&mdash;/gi, "-")
    .replace(/&ndash;/gi, "-")
    .replace(/&hellip;/gi, "...")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)));
}

function stripTags(input: string): string {
  return decodeEntities(input.replace(/<[^>]+>/g, " "))
    .replace(/\s+/g, " ")
    .trim();
}

function truncate(input: string, max: number): string {
  if (input.length <= max) return input;
  return input.slice(0, max - 1).replace(/[\s,;:.-]+$/, "") + "\u2026";
}

/** Paths that are navigation or plumbing rather than content. */
const IGNORED_PATH = /\/(login|signin|sign-in|signup|sign-up|register|cart|checkout|account|search|tag|tags|category|categories|page\/\d+)(\/|$)/i;

/** A bare language prefix such as /nl or /en-gb is a switcher, not a page. */
const LOCALE_ONLY = /^\/[a-z]{2}(-[a-z]{2})?$/i;

/** If the last segment looks like a file, it must not get a trailing slash. */
const FILE_LIKE = /\.[a-z0-9]{2,5}$/i;

/** Turn "/customer-stories" into "Customer stories" for anchors with no text. */
function pathLabel(path: string): string {
  if (path === "/") return "Home";
  const segment = path.split("/").filter(Boolean).pop() || "";
  const words = segment.replace(/[-_]+/g, " ").trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/**
 * The text a reader would call the link.
 *
 * When a whole card is wrapped in one anchor, the raw text is the entire card -
 * emoji, heading and paragraph together - which fills the file with truncated
 * 80-character labels. The heading or bold run inside the anchor is what the
 * link is actually called, so it wins when present.
 */
function anchorLabel(inner: string): string {
  const heading = inner.match(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i)?.[1];
  if (heading) return truncate(stripTags(heading), 60);
  const bold = inner.match(/<(strong|b)\b[^>]*>([\s\S]*?)<\/\1>/i)?.[2];
  if (bold) return truncate(stripTags(bold), 60);
  return truncate(stripTags(inner), 60);
}

type LinkEntry = { path: string; url: string; label: string };

function extractLinks(html: string, origin: string, host: string): LinkEntry[] {
  const seen = new Set<string>();
  const out: LinkEntry[] = [];
  const re = /<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;

  let match: RegExpExecArray | null;
  while ((match = re.exec(html)) !== null) {
    if (out.length >= 400) break;

    const rawHref = match[1].trim();
    if (!rawHref || rawHref.startsWith("#")) continue;
    if (/^(mailto:|tel:|javascript:)/i.test(rawHref)) continue;

    let url: URL;
    try {
      url = new URL(rawHref, origin);
    } catch {
      continue;
    }
    if (url.hostname.replace(/^www\./, "") !== host) continue;
    if (/\.(jpg|jpeg|png|gif|svg|webp|pdf|zip|mp4|css|js)$/i.test(url.pathname)) continue;
    if (IGNORED_PATH.test(url.pathname)) continue;

    const path = url.pathname.replace(/\/+$/, "") || "/";
    if (seen.has(path)) continue;

    // Anchors that wrap only an image carry no text. Falling back to a
    // humanised path beats emitting a raw "/nl/products" as a label, and beats
    // dropping a page that may well be worth listing.
    const rawLabel = anchorLabel(match[2]);

    // A bare language prefix with no link text is a language switcher rather
    // than a destination. With text - "Deutsch", "Nederlands" - it points at a
    // real localised page, and dropping those would omit exactly the pages a
    // multilingual site most wants listed.
    if (LOCALE_ONLY.test(path) && !rawLabel) continue;

    seen.add(path);
    const label = rawLabel || pathLabel(path);

    // Only directories get a trailing slash. Appending one to /llms.txt turns a
    // valid file URL into a 404, which is the exact failure this file is meant
    // to help people avoid.
    const suffix = FILE_LIKE.test(path) ? "" : "/";
    out.push({ path, url: `${origin}${path}${suffix}`, label });
  }
  return out;
}

export async function GET(request: Request) {
  // Before any parsing or fetching. See lib/net/rate-limit.ts for what this
  // does and does not enforce.
  const limit = takeToken(clientKey(request));
  if (!limit.allowed) {
    return NextResponse.json(
      {
        error: "Too many requests from this address. Please wait a moment and try again.",
        retryAfter: limit.retryAfter,
      },
      { status: 429, headers: { "Retry-After": String(limit.retryAfter) } }
    );
  }

  const { searchParams } = new URL(request.url);
  const domain = cleanDomain(searchParams.get("domain") || "");

  /**
   * Content is requested in the language of the page the user is on.
   *
   * Without this the edge worker's own location decides: requesting stripe.com
   * from a Netherlands-based edge node returned Stripe's Dutch homepage, so the
   * generated file described the site in a language its owner may not publish
   * in. Sending Accept-Language makes the result predictable and lets the
   * German studio produce German copy for German sites.
   */
  const langParam = (searchParams.get("lang") || "en").toLowerCase();
  const lang = /^[a-z]{2}$/.test(langParam) ? langParam : "en";
  const acceptLanguage = lang === "en" ? "en-US,en;q=0.9" : `${lang},en;q=0.5`;

  if (!domain || !/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(domain)) {
    return NextResponse.json({ error: "Invalid domain" }, { status: 400 });
  }

  // Reject targets that point at a network rather than a website, and say why.
  const target = inspectTarget(`https://${domain}`);
  if (!target.ok) {
    return NextResponse.json({ reachable: false, error: target.reason }, { status: 400 });
  }

  const origin = `https://${domain}`;
  const fetched = await fetchText(origin, {
    userAgent: UA,
    accept: "text/html,application/xhtml+xml,*/*",
    acceptLanguage,
    timeoutMs: FETCH_TIMEOUT_MS,
  });

  const status = fetched?.status ?? 0;
  const html = fetched && fetched.status >= 200 && fetched.status < 300 ? fetched.body : "";

  if (!html) {
    return NextResponse.json(
      {
        error:
          status === 0
            ? "The homepage could not be reached."
            : `The homepage returned HTTP ${status}.`,
        reachable: false,
        status,
      },
      { status: 200 }
    );
  }

  const titleTag = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const h1Tag = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  const descTag = html.match(
    /<meta[^>]+name\s*=\s*["']description["'][^>]*content\s*=\s*["']([\s\S]*?)["']/i
  );

  // Titles commonly carry a tagline after a separator; the part before it is the
  // site name far more often than not.
  const rawTitle = titleTag ? stripTags(titleTag[1]) : "";
  const siteName =
    truncate(rawTitle.split(/\s+[|\u2013\u2014\u00b7-]\s+/)[0] || "", 70) ||
    (h1Tag ? truncate(stripTags(h1Tag[1]), 70) : "") ||
    domain;

  const description = descTag
    ? truncate(stripTags(descTag[1]), 200)
    : h1Tag
      ? truncate(stripTags(h1Tag[1]), 200)
      : "";

  const links = extractLinks(html, origin, domain).slice(0, MAX_LINKS);
  const today = new Date().toISOString().slice(0, 10);

  const lines: string[] = [];
  /**
   * Boilerplate in the language of the tool the reader is using.
   *
   * The German studio used to emit an English file: German headings, German
   * buttons, and then "## Key pages" and English notes inside the output a
   * German site owner is meant to publish. The fetched content already differs
   * by language - Accept-Language decides that - so the surrounding scaffolding
   * has to follow it.
   */
  const L = OUTPUT_LABELS[lang] ?? OUTPUT_LABELS.en;

  lines.push(`# ${siteName}`);
  lines.push("");
  if (description) {
    lines.push(`> ${description}`);
    lines.push("");
  }
  lines.push(L.intro(siteName, origin));
  lines.push("");
  lines.push(L.keyPages);
  lines.push("");
  if (links.length === 0) {
    lines.push(L.homeFallback(origin));
  } else {
    for (const link of links) {
      const label = link.label || link.path;
      lines.push(`- [${label}](${link.url})`);
    }
  }
  lines.push("");
  lines.push(L.notes);
  lines.push("");
  lines.push(L.generatedBy(today, origin));
  lines.push(L.review);
  lines.push(L.convention);

  return NextResponse.json({
    reachable: true,
    status,
    domain,
    siteName,
    description,
    linkCount: links.length,
    content: lines.join("\n") + "\n",
  });
}
